const cats = [
  {
    id: 'c001',
    name: 'Кот полосатый',
    color: 'Коричневый',
    age: 3,
    paws: 4,
    price: 30000,
    isLiked: false,
    discount: '40',
    img: {
      name: 'cat-1',
      format: 'jpg',
      alt: 'Умный котик',
    },
  },
  {
    id: 'c002',
    name: 'Кот полосатый',
    color: 'Коричневый',
    age: 4,
    paws: 4,
    price: 40000,
    isLiked: true,
    isSoldOut: true,
    img: {
      name: 'cat-3',
      format: 'jpg',
      alt: 'Уставший котик',
    },
  },
  {
    id: 'c003',
    name: 'Кот полосатый',
    color: 'Коричневый',
    age: 2,
    paws: 4,
    price: 20000,
    isLiked: false,
    img: {
      name: 'cat-2',
      format: 'jpg',
      alt: 'Серьезный котик',
    },
  },
  {
    id: 'c004',
    name: 'Кот полосатый',
    color: 'Коричневый',
    age: 1,
    paws: 4,
    price: 25000,
    img: {
      name: 'cat-1',
      format: 'jpg',
    },
  },
  {
    id: 'c005',
    name: 'Кот полосатый',
    color: 'Коричневый',
    age: 2,
    paws: 4,
    price: 30000,
    isLiked: false,
    discount: '40',
    img: {
      name: 'cat-2',
      format: 'jpg',
      alt: 'Серьезный котик',
    },
  },
  {
    id: 'c006',
    name: 'Кот полосатый',
    color: 'Коричневый',
    age: 3,
    paws: 4,
    price: 10000,
    isLiked: true,
    isSoldOut: true,
    img: {
      name: 'cat-3',
      format: 'jpg',
      alt: 'Уставший котик',
    },
  }
];

export default cats;
